import { TRAINING_STATUS } from '../../common/constants/training-status.constants';

export const TRAINING_FLOW_TRANSITIONS: Record<string, string[]> = {
  [TRAINING_STATUS.PAYMENT_REQUIRED]: [TRAINING_STATUS.PAYMENT_WAITING],

  [TRAINING_STATUS.PAYMENT_WAITING]: [TRAINING_STATUS.PAYMENT_VERIFIED],

  [TRAINING_STATUS.PAYMENT_VERIFIED]: [TRAINING_STATUS.ADMINISTRATIVE_REQUIRED],

  [TRAINING_STATUS.ADMINISTRATIVE_REQUIRED]: [TRAINING_STATUS.WAITING_ADMINISTRATIVE],

  [TRAINING_STATUS.WAITING_ADMINISTRATIVE]: [TRAINING_STATUS.ARTICLE_WAITING],

  [TRAINING_STATUS.ARTICLE_WAITING]: [TRAINING_STATUS.ARTICLE_VERIFIED],

  [TRAINING_STATUS.ARTICLE_VERIFIED]: [TRAINING_STATUS.TRAINING_WAITING],

  [TRAINING_STATUS.TRAINING_WAITING]: [
    TRAINING_STATUS.TRAINING_VERIFIED,
    TRAINING_STATUS.TRAINING_RESCHEDULE,
  ],

  [TRAINING_STATUS.TRAINING_RESCHEDULE]: [
    TRAINING_STATUS.TRAINING_WAITING,
  ],

  [TRAINING_STATUS.TRAINING_VERIFIED]: [TRAINING_STATUS.REVIEW_WAITING],

  [TRAINING_STATUS.REVIEW_WAITING]: [
    TRAINING_STATUS.REVIEW_VERIFIED,
    TRAINING_STATUS.REVIEW_REVISION
  ],

  [TRAINING_STATUS.REVIEW_REVISION]: [
    TRAINING_STATUS.REVIEW_WAITING,
  ],

  [TRAINING_STATUS.REVIEW_VERIFIED]: [TRAINING_STATUS.LOA_WAITING],

  [TRAINING_STATUS.LOA_WAITING]: [TRAINING_STATUS.LOA_PUBLISHED],
};

export interface TransitionContext {
  userId: string;
  actorRole: string;
}

export const transitionPaymentWaiting = async (context: TransitionContext) => {
  // Logic: Update status to PAYMENT_WAITING, validasi PAYMENT_REQUIRED
  console.log('Transition to PAYMENT_WAITING', context);
  // Call TrainingFlowService.update
};