export const TRAINING_STATUS = {
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PAYMENT_WAITING: 'PAYMENT_WAITING',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',

  ADMINISTRATIVE_REQUIRED: 'ADMINISTRATIVE_REQUIRED',
  WAITING_ADMINISTRATIVE: 'WAITING_ADMINISTRATIVE',

  ARTICLE_WAITING: 'ARTICLE_WAITING',
  ARTICLE_VERIFIED: 'ARTICLE_VERIFIED',

  TRAINING_WAITING: 'TRAINING_WAITING',
  TRAINING_VERIFIED: 'TRAINING_VERIFIED',
  TRAINING_RESCHEDULE: 'TRAINING_RESCHEDULE',

  REVIEW_WAITING: 'REVIEW_WAITING',
  REVIEW_VERIFIED: 'REVIEW_VERIFIED',

  LOA_WAITING: 'LOA_WAITING',
  LOA_PUBLISHED: 'LOA_PUBLISHED',
} as const;

export type TrainingStatus = (typeof TRAINING_STATUS)[keyof typeof TRAINING_STATUS];
